"""Rebuild offline /ops fonts. Development only; requires fonttools[woff]."""
from pathlib import Path
import argparse
import base64
import hashlib
import json
from fontTools.ttLib import TTFont
from fontTools import subset

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('source_dir', type=Path, help='Directory containing the upstream TTF files listed in README.md')
args = parser.parse_args()
here = Path(__file__).resolve().parent
root = here.parents[1]
faces = [
    ('Barlow-Regular', 'Barlow', '400'),
    ('Barlow-Medium', 'Barlow', '500'),
    ('Barlow-SemiBold', 'Barlow', '600'),
    ('BarlowCondensed-Medium', 'Barlow Condensed', '500'),
    ('BarlowCondensed-SemiBold', 'Barlow Condensed', '600'),
    ('IBMPlexMono-Regular', 'IBM Plex Mono', '400'),
    ('NotoSansSC-full', 'Noto Sans SC', '100 900'),
]
manifest = {}
manifest_path = here / "manifest.json"
previous = json.loads(manifest_path.read_text()) if manifest_path.exists() else {}
css = ['/* BEGIN LOCAL FONTS — generated by assets/fonts/embed.py; licenses beside script. */']
for name, family, weight in faces:
    source = args.source_dir / (name + '.ttf')
    source_hash = hashlib.sha256(source.read_bytes()).hexdigest()
    cached = previous.get(source.name, {})
    cached_target = here / (name + '.woff2')
    reuse = (family != 'Noto Sans SC' and cached_target.exists()
             and cached.get('source_sha256') == source_hash
             and cached.get('output_sha256') == hashlib.sha256(cached_target.read_bytes()).hexdigest())
    font = None if reuse else TTFont(source, recalcTimestamp=False)
    output_name = name
    if family == 'Noto Sans SC':
        # Only UI glyphs are subset locally. Arbitrary received text uses the system
        # CJK fallback for absent glyphs, rather than requesting a remote font.
        text = ''.join((root / f).read_text() for f in ['dashboard-b.html', 'dashboard-b-client.js', 'data.html', 'admin.html', 'farm-connection.js', 'workbench.js'])
        options = subset.Options()
        options.name_IDs = ['*']
        options.name_legacy = True
        options.name_languages = ['*']
        sub = subset.Subsetter(options=options)
        sub.populate(unicodes={ord(c) for c in text if ord(c) > 255})
        sub.subset(font)
        output_name = 'NotoSansSC-UI'
    target = here / (output_name + '.woff2')
    if not reuse:
        font.flavor = 'woff2'
        font.save(target)
    payload = target.read_bytes()
    manifest[source.name] = {'source_sha256': hashlib.sha256(source.read_bytes()).hexdigest(),
                             'output': target.name, 'output_sha256': hashlib.sha256(payload).hexdigest()}
    encoded = base64.b64encode(payload).decode()
    css.append(f'@font-face {{font-family:"{family}";font-style:normal;font-weight:{weight};font-display:swap;src:url(data:font/woff2;base64,{encoded}) format("woff2");}}')
css.append('/* END LOCAL FONTS */')
path = root / 'ops.css'
styles = path.read_text()
if styles.startswith('/* BEGIN LOCAL FONTS'):
    styles = styles.split('/* END LOCAL FONTS */', 1)[1].lstrip('\n')
path.write_text('\n'.join(css) + '\n\n' + styles)
(here / 'manifest.json').write_text(json.dumps(manifest, indent=2) + '\n')
print(f'Embedded {len(faces)} local faces; stylesheet {path.stat().st_size:,} bytes')
